apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyrolyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyrolyzer
  template:
    metadata:
      name: pyrolyzer
      labels:
        app: pyrolyzer
    spec:
      containers:
      - name: pyrolyzer
        image: pyrolyzer/cit270
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.coleman
---
apiVersion: v1
kind: Service
metadata:
  name: pyrolyzer-loadbalancer
spec:
  selector:
    app: pyrolyzer
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443